name: Publish Gem
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run :
          cat << EOF > ~/.gem/credentials
          ---
          :github: Bearer ${{ secrets.GITHUB_TOKEN }}
          :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          EOF
      - run: bundle install
      - name: Release Gem
        run: rake release
