name: Publish
on:
  push:
    branches:
      - master

jobs:
  build:
    steps:
      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
